ALTER TABLE public.evaluations
  ADD COLUMN IF NOT EXISTS market_type text,
  ADD COLUMN IF NOT EXISTS currency text,
  ADD COLUMN IF NOT EXISTS entry_price numeric,
  ADD COLUMN IF NOT EXISTS exit_price numeric,
  ADD COLUMN IF NOT EXISTS quantity numeric,
  ADD COLUMN IF NOT EXISTS lot_size numeric,
  ADD COLUMN IF NOT EXISTS contract_size numeric,
  ADD COLUMN IF NOT EXISTS leverage numeric,
  ADD COLUMN IF NOT EXISTS margin numeric,
  ADD COLUMN IF NOT EXISTS notional_value numeric,
  ADD COLUMN IF NOT EXISTS stop_loss numeric,
  ADD COLUMN IF NOT EXISTS take_profit numeric,
  ADD COLUMN IF NOT EXISTS gross_pnl numeric,
  ADD COLUMN IF NOT EXISTS fees numeric,
  ADD COLUMN IF NOT EXISTS net_pnl numeric,
  ADD COLUMN IF NOT EXISTS price_change_percent numeric,
  ADD COLUMN IF NOT EXISTS roi_margin numeric,
  ADD COLUMN IF NOT EXISTS risk_amount numeric,
  ADD COLUMN IF NOT EXISTS risk_percent numeric,
  ADD COLUMN IF NOT EXISTS planned_rr numeric,
  ADD COLUMN IF NOT EXISTS realized_rr numeric,
  ADD COLUMN IF NOT EXISTS trade_result text,
  ADD COLUMN IF NOT EXISTS post_trade_inputs jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS calculated_at timestamp with time zone;